In [81]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

%matplotlib inline
pd.set_option('display.max_columns', None)

In [82]:
df = pd.read_csv('online_shoppers_intention.csv')

In [83]:
df.head()

Administrative  Administrative_Duration  Informational  \
0               0                      0.0              0   
1               0                      0.0              0   
2               0                      0.0              0   
3               0                      0.0              0   
4               0                      0.0              0   

   Informational_Duration  ProductRelated  ProductRelated_Duration  \
0                     0.0               1                 0.000000   
1                     0.0               2                64.000000   
2                     0.0               1                 0.000000   
3                     0.0               2                 2.666667   
4                     0.0              10               627.500000   

   BounceRates  ExitRates  PageValues  SpecialDay Month  OperatingSystems  \
0         0.20       0.20         0.0         0.0   Feb                 1   
1         0.00       0.10         0.0         0.0   Feb                 2   
2         0.20       0.20         0.0         0.0   Feb                 4   
3         0.05       0.14         0.0         0.0   Feb                 3   
4         0.02       0.05         0.0         0.0   Feb                 3   

   Browser  Region  TrafficType        VisitorType  Weekend  Revenue  
0        1       1            1  Returning_Visitor    False    False  
1        2       1            2  Returning_Visitor    False    False  
2        1       9            3  Returning_Visitor    False    False  
3        2       2            4  Returning_Visitor    False    False  
4        3       1            4  Returning_Visitor     True    False

In [84]:
df.tail()

Administrative  Administrative_Duration  Informational  \
12325               3                    145.0              0   
12326               0                      0.0              0   
12327               0                      0.0              0   
12328               4                     75.0              0   
12329               0                      0.0              0   

       Informational_Duration  ProductRelated  ProductRelated_Duration  \
12325                     0.0              53              1783.791667   
12326                     0.0               5               465.750000   
12327                     0.0               6               184.250000   
12328                     0.0              15               346.000000   
12329                     0.0               3                21.250000   

       BounceRates  ExitRates  PageValues  SpecialDay Month  OperatingSystems  \
12325     0.007143   0.029031   12.241717         0.0   Dec                 4   
12326     0.000000   0.021333    0.000000         0.0   Nov                 3   
12327     0.083333   0.086667    0.000000         0.0   Nov                 3   
12328     0.000000   0.021053    0.000000         0.0   Nov                 2   
12329     0.000000   0.066667    0.000000         0.0   Nov                 3   

       Browser  Region  TrafficType        VisitorType  Weekend  Revenue  
12325        6       1            1  Returning_Visitor     True    False  
12326        2       1            8  Returning_Visitor     True    False  
12327        2       1           13  Returning_Visitor     True    False  
12328        2       3           11  Returning_Visitor    False    False  
12329        2       1            2        New_Visitor     True    False

In [85]:
df.shape

(12330, 18)

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12330 entries, 0 to 12329
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Administrative           12330 non-null  int64  
 1   Administrative_Duration  12330 non-null  float64
 2   Informational            12330 non-null  int64  
 3   Informational_Duration   12330 non-null  float64
 4   ProductRelated           12330 non-null  int64  
 5   ProductRelated_Duration  12330 non-null  float64
 6   BounceRates              12330 non-null  float64
 7   ExitRates                12330 non-null  float64
 8   PageValues               12330 non-null  float64
 9   SpecialDay               12330 non-null  float64
 10  Month                    12330 non-null  object 
 11  OperatingSystems         12330 non-null  int64  
 12  Browser                  12330 non-null  int64  
 13  Region                   12330 non-null  int64  
 14  TrafficType           

In [87]:
df.describe()

Administrative  Administrative_Duration  Informational  \
count    12330.000000             12330.000000   12330.000000   
mean         2.315166                80.818611       0.503569   
std          3.321784               176.779107       1.270156   
min          0.000000                 0.000000       0.000000   
25%          0.000000                 0.000000       0.000000   
50%          1.000000                 7.500000       0.000000   
75%          4.000000                93.256250       0.000000   
max         27.000000              3398.750000      24.000000   

       Informational_Duration  ProductRelated  ProductRelated_Duration  \
count            12330.000000    12330.000000             12330.000000   
mean                34.472398       31.731468              1194.746220   
std                140.749294       44.475503              1913.669288   
min                  0.000000        0.000000                 0.000000   
25%                  0.000000        7.000000               184.137500   
50%                  0.000000       18.000000               598.936905   
75%                  0.000000       38.000000              1464.157214   
max               2549.375000      705.000000             63973.522230   

        BounceRates     ExitRates    PageValues    SpecialDay  \
count  12330.000000  12330.000000  12330.000000  12330.000000   
mean       0.022191      0.043073      5.889258      0.061427   
std        0.048488      0.048597     18.568437      0.198917   
min        0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.014286      0.000000      0.000000   
50%        0.003112      0.025156      0.000000      0.000000   
75%        0.016813      0.050000      0.000000      0.000000   
max        0.200000      0.200000    361.763742      1.000000   

       OperatingSystems       Browser        Region   TrafficType  
count      12330.000000  12330.000000  12330.000000  12330.000000  
mean           2.124006      2.357097      3.147364      4.069586  
std            0.911325      1.717277      2.401591      4.025169  
min            1.000000      1.000000      1.000000      1.000000  
25%            2.000000      2.000000      1.000000      2.000000  
50%            2.000000      2.000000      3.000000      2.000000  
75%            3.000000      2.000000      4.000000      4.000000  
max            8.000000     13.000000      9.000000     20.000000

In [88]:
df.isnull().sum()

Administrative             0
Administrative_Duration    0
Informational              0
Informational_Duration     0
ProductRelated             0
ProductRelated_Duration    0
BounceRates                0
ExitRates                  0
PageValues                 0
SpecialDay                 0
Month                      0
OperatingSystems           0
Browser                    0
Region                     0
TrafficType                0
VisitorType                0
Weekend                    0
Revenue                    0
dtype: int64

In [89]:
# Ver porcentaje de valores faltantes

df.isnull().sum()/len(df)*100

Administrative             0.0
Administrative_Duration    0.0
Informational              0.0
Informational_Duration     0.0
ProductRelated             0.0
ProductRelated_Duration    0.0
BounceRates                0.0
ExitRates                  0.0
PageValues                 0.0
SpecialDay                 0.0
Month                      0.0
OperatingSystems           0.0
Browser                    0.0
Region                     0.0
TrafficType                0.0
VisitorType                0.0
Weekend                    0.0
Revenue                    0.0
dtype: float64

In [90]:
df.eq(' ').sum()

Administrative             0
Administrative_Duration    0
Informational              0
Informational_Duration     0
ProductRelated             0
ProductRelated_Duration    0
BounceRates                0
ExitRates                  0
PageValues                 0
SpecialDay                 0
Month                      0
OperatingSystems           0
Browser                    0
Region                     0
TrafficType                0
VisitorType                0
Weekend                    0
Revenue                    0
dtype: int64

In [91]:
# No hay valores faltantes

In [92]:
df.duplicated().sum()

125

In [93]:
df = df.drop_duplicates()

In [94]:
df.head(2)

Administrative  Administrative_Duration  Informational  \
0               0                      0.0              0   
1               0                      0.0              0   

   Informational_Duration  ProductRelated  ProductRelated_Duration  \
0                     0.0               1                      0.0   
1                     0.0               2                     64.0   

   BounceRates  ExitRates  PageValues  SpecialDay Month  OperatingSystems  \
0          0.2        0.2         0.0         0.0   Feb                 1   
1          0.0        0.1         0.0         0.0   Feb                 2   

   Browser  Region  TrafficType        VisitorType  Weekend  Revenue  
0        1       1            1  Returning_Visitor    False    False  
1        2       1            2  Returning_Visitor    False    False

In [95]:
df['Revenue'].unique()

array([False,  True])

In [96]:
df.eq(' ').sum().sort_values(ascending=False)

Administrative             0
Administrative_Duration    0
Weekend                    0
VisitorType                0
TrafficType                0
Region                     0
Browser                    0
OperatingSystems           0
Month                      0
SpecialDay                 0
PageValues                 0
ExitRates                  0
BounceRates                0
ProductRelated_Duration    0
ProductRelated             0
Informational_Duration     0
Informational              0
Revenue                    0
dtype: int64

In [97]:
df.Browser.unique()

array([ 1,  2,  3,  4,  5,  6,  7, 10,  8,  9, 12, 13, 11], dtype=int64)

identificamos que algunas columnas del dataset están codificadas numéricamente. Para facilitar la interpretación y mejorar la visualización en el análisis exploratorio de datos (EDA), asignaremos nombres descriptivos a estas columnas mediante un proceso de mapeo. Esto nos permitirá analizar los datos de manera más clara y comprensible.

In [98]:
browser_mapping = {
    1: "Chrome",
    2: "Safari",
    3: "Internet Explorer",
    4: "Firefox",
    5: "Edge",
    6: "Opera",
    7: "Otros",
    8: "Otros",
    9: "Otros",
    10: "Otros",
    11: "Otros",
    12: "Otros",
    13: "Otros"
}

In [99]:
df['Browser_Label'] = df['Browser'].map(browser_mapping)

In [100]:
df.tail()

Administrative  Administrative_Duration  Informational  \
12325               3                    145.0              0   
12326               0                      0.0              0   
12327               0                      0.0              0   
12328               4                     75.0              0   
12329               0                      0.0              0   

       Informational_Duration  ProductRelated  ProductRelated_Duration  \
12325                     0.0              53              1783.791667   
12326                     0.0               5               465.750000   
12327                     0.0               6               184.250000   
12328                     0.0              15               346.000000   
12329                     0.0               3                21.250000   

       BounceRates  ExitRates  PageValues  SpecialDay Month  OperatingSystems  \
12325     0.007143   0.029031   12.241717         0.0   Dec                 4   
12326     0.000000   0.021333    0.000000         0.0   Nov                 3   
12327     0.083333   0.086667    0.000000         0.0   Nov                 3   
12328     0.000000   0.021053    0.000000         0.0   Nov                 2   
12329     0.000000   0.066667    0.000000         0.0   Nov                 3   

       Browser  Region  TrafficType        VisitorType  Weekend  Revenue  \
12325        6       1            1  Returning_Visitor     True    False   
12326        2       1            8  Returning_Visitor     True    False   
12327        2       1           13  Returning_Visitor     True    False   
12328        2       3           11  Returning_Visitor    False    False   
12329        2       1            2        New_Visitor     True    False   

      Browser_Label  
12325         Opera  
12326        Safari  
12327        Safari  
12328        Safari  
12329        Safari

In [101]:
df.VisitorType.unique()

array(['Returning_Visitor', 'New_Visitor', 'Other'], dtype=object)

In [102]:
df.Month.unique()

array(['Feb', 'Mar', 'May', 'Oct', 'June', 'Jul', 'Aug', 'Nov', 'Sep',
       'Dec'], dtype=object)

In [103]:
df.SpecialDay.unique()

array([0. , 0.4, 0.8, 1. , 0.2, 0.6])

In [104]:
df.OperatingSystems.unique()

array([1, 2, 4, 3, 7, 6, 8, 5], dtype=int64)

In [105]:
os_mapping = {
    1: "Windows",
    2: "MacOS",
    3: "Linux",
    4: "Android",
    5: "iOS",
    6: "Other",
    7: "Other",
    8: "Other"
}

In [106]:
df['OS_Label'] = df['OperatingSystems'].map(os_mapping)

In [107]:
df.Region.unique()

array([1, 9, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [108]:
region_mapping = {
    1: "NorthAmerica",
    2: "Europe",
    3: "Asia",
    4: "SouthAmerica",
    5: "Africa",
    6: "Oceania",
    7: "MiddleEast",
    8: "Antarctica",
    9: "Other"
}

In [109]:
df['Region_Label'] = df['Region'].map(region_mapping)

In [110]:
df.TrafficType.nunique()

20

In [111]:
traffic_mapping = {
    1: "Organic Traffic",
    2: "Direct Traffic",
    3: "Referral Traffic",
    4: "Paid Traffic",
    5: "Social Media",
    6: "Email Marketing",
    7: "Other",
    8: "Other",
    9: "Other",
    10: "Other",
    11: "Other",
    12: "Other",
    13: "Other",
    14: "Other",
    15: "Other",
    16: "Other",
    17: "Other",
    18: "Other",
    19: "Other",
    20: "Other"
}

In [112]:
df['Traffic_Type_Label'] = df['TrafficType'].map(traffic_mapping)

In [113]:
df['VisitorType'] = df['VisitorType'].str.replace('_', ' ')


In [114]:
column_mapping = {
    "ProductRelated": "Product_Related",
    "ProductRelated_Duration": "Product_Related_Duration",
    "BounceRates": "Bounce_Rates",
    "ExitRates": "Exit_Rates",
    "PageValues": "Page_Values",
    "SpecialDay": "Special_Day",
    "OperatingSystems": "Operating_Systems",
    "TrafficType": "Traffic_Type",
    "VisitorType": "Visitor_Type"
}

In [115]:
df.rename(columns=column_mapping, inplace=True)

In [116]:
df.columns = [col.capitalize() for col in df.columns]

In [122]:
df.sample(5)

Administrative  Administrative_duration  Informational  \
3617                0                 0.000000              0   
8232                5                70.333333              0   
8600                6               148.208333              2   
6705                0                 0.000000              0   
10386               3                77.500000              0   

       Informational_duration  Product_related  Product_related_duration  \
3617                      0.0               11                855.250000   
8232                      0.0               29               1049.313889   
8600                    139.5               98               3714.352664   
6705                      0.0               91               4157.633333   
10386                     0.0               35               1000.800000   

       Bounce_rates  Exit_rates  Page_values  Special_day Month  \
3617       0.018182    0.063636          0.0          0.0   May   
8232       0.025595    0.054241          0.0          0.0   Nov   
8600       0.005000    0.013430          0.0          0.0   Nov   
6705       0.010000    0.028013          0.0          0.0   Jul   
10386      0.000000    0.013889          0.0          0.0   Dec   

       Operating_systems  Browser  Region  Traffic_type       Visitor_type  \
3617                   2        2       3            13  Returning Visitor   
8232                   3        2       3             2  Returning Visitor   
8600                   2        2       1             2  Returning Visitor   
6705                   2        2       1            13  Returning Visitor   
10386                  4        2       1             6  Returning Visitor   

       Weekend  Revenue Browser_label Os_label  Region_label  \
3617     False    False        Safari    MacOS          Asia   
8232      True    False        Safari    Linux          Asia   
8600     False    False        Safari    MacOS  NorthAmerica   
6705     False    False        Safari    MacOS  NorthAmerica   
10386    False    False        Safari  Android  NorthAmerica   

      Traffic_type_label  
3617               Other  
8232      Direct Traffic  
8600      Direct Traffic  
6705               Other  
10386    Email Marketing

In [118]:
df.shape

(12205, 22)

In [119]:
df1 = df.copy()

In [120]:
df1.to_csv('online_shoppers_intentions_clean.csv', index=False)